### ISSUE TITLE
Dumpling fails to detect discs

### ISSUE THREAD

**Issue by lemoncove** [emiyl/dumpling#20]
I'm assuming this is a result of today's update in which disc detection was modified. No discs are being recognized, including ones I successfully dumped yesterday/earlier today.

**Comment by Crementif** [comment]
Are you using Tiramisu or just launching Dumpling directly via https://dumplingapp.com.

**Comment by lemoncove** [comment]
I'm using the https://dumplingapp.com/ web launcher.
