### ISSUE TITLE
Selecting "Exit Dumpling" option causes Dumpling to restart

### ISSUE THREAD

**Issue by lemoncove** [emiyl/dumpling#21]
I'm assuming this is a result of today's update. To turn off the Wii U I have to hold the power button now. I'm using the standalone web version.

**Comment by Crementif** [comment]
I'm fairly certain the regression is fixed, at least when I tested it. You can let me know if you're still experiencing the issue, but otherwise I'll close it soon:tm:.

**Comment by lemoncove** [comment]
Yep, seems fixed.

**Comment by Crementif** [comment]
Thanks for reporting it on Github, made me able to fix it pretty quickly!

**Comment by wtquin** [comment]
Getting this same exact problem with the latest release (v2.5.0) on my wii u (5.5.x) when using the standalone web version (dumplingapp.com). Here's a video showing 2 cycles: https://streamable.com/w79hvf
