### ISSUE TITLE
Dumpling may stop dumping a disc prematurely with no error presented.

### ISSUE THREAD

**Issue by sensed0ff** [emiyl/dumpling#22]
When dumping a disc based game, the user is sent back into the main menu when the process is over. I had this happen even when a game stated to be 11GB was ripped in less than 30 minutes (I later realized my Wii U isn't able to read the disc anymore, but I suspect that its disc drive may be defective given past experiences with it rather than a bad disc.).

It would be incredibly helpful if a message stating whether or not it succeeded was presented, which is what happens when dumping installed games, at least when successful.

I was worried that the two discs I ripped beforehand may not have been correctly copied, but I'm assuming they were given that NUSPacker was able to produce files that WUP Installer GX2 could write to my Wii U's USB drive and I was able to actually play them.

I'd also like to say I'm very grateful to you all and the rest of the homebrew community for making this all possible!

**Comment by Crementif** [comment]
Dumpling should give much better errors (and general stability should also be better) with the latest version I just released, please try it out if you can. I can't really replicate it myself, so it'd be very helpful.

**Comment by Crementif** [comment]
This issue was reproduced locally and is now fixed in a previous release!
