### ISSUE TITLE
When dumping a disc, it dumps DLC regardless of whether you said yes or no

### ISSUE THREAD

**Issue by raziel2001au** [emiyl/dumpling#24]
I'm having trouble dumping my copy of Xenoblade Chronicles X as I only have a 32GB SD card. If you choose to dump a disc, it asks if you want to also dump the DLC and updates, even if you say no, it still dumps the DLC anyway (and likely updates too), so my 32GB cart ends up not being large enough for the dump with it running out of space on some of the DLC files. If it only dumped the disc and updates it shouldn't be a problem. If you choose to just dump the base game, it doesn't show the disc, so that path doesn't work either.

Am I doing something wrong?

**Comment by Crementif** [comment]
I've heard that the prompt to only dump the games might be buggy/inverted.

Before I fix it, you could uninstall the update and base game from the Wii U. Alternatively you can just quit dumping after it has finished the base game, and then dump the online files and use Cemu's download manager to dump the updates. We describe it at https://cemu.cfw.guide/dumping-games.

**Comment by raziel2001au** [comment]
While I haven't done a full dump to test, on the surface it looks like you're right, the option seems to be inverted, when I selected 'yes' (I do want it to dump DLC and updates) it's now saying the dump will need 20GB, which is more like what I expected.

**Comment by Crementif** [comment]
Should be fixed with the current release!
