### ISSUE TITLE
I have a scratched disk and I want to know if a feature for continuing from failed dumps is possible.

### ISSUE THREAD

**Issue by Wiiuhomebrewer** [emiyl/dumpling#26]
My disk gets ERROR 5 every time I try to dump it and I don't want to start from ground zero every time, I don't know if this is way too hard to code but is it possible to make this feature?

**Comment by Crementif** [comment]
I mean it's possible, but I'm not sure if scratches are able to be fixed by retrying.

**Comment by Wiiuhomebrewer** [comment]
I forgot I left a issue here, I bought smash 4 a week ago as a replacement.
I was extremely desperate to not spend money on a game I had already paid but sometimes life is a pain in the ass
