### ISSUE TITLE
Unable to Dump Some Japanese VC Titles

### ISSUE THREAD

**Issue by ValadAmoleo** [emiyl/dumpling#31]
Just going through dumping all my titles from my Japanese Wii U and I came across two that refused to dump

バハムート ラグーン  (Bahamut Lagoon - SNES)
ヘラクレスの栄光Ⅲ 神々の沈黙 (Glory of Heracles III - SNES)

It just produced "An error has occurred", tried on both SD card and USB.  I worked around this by dumping the entire MLC using Dumpling, the two troublesome games were dumped successfully.

**Comment by Crementif** [comment]
Should be fixed in the latest release. Let me know if it's working now, and if not I'll spend some more time on it.
