### ISSUE TITLE
Dumping Titles Without English Name

### ISSUE THREAD

**Issue by redman-tsai** [emiyl/dumpling#32]
Hi:

I tried to dump some VC titles on my Japanese WiiU. Because they have no English title names, dumpling will not create a folder with the game title and dump all in the Games folder, this makes I can only dump one game at a time. Is it possible to use the product code as the folder name if normalise title name (longname_ja) is empty? Basically adding a check after this line: https://github.com/emiyl/dumpling/blob/89f85c65390aff69165e59b1c8c8172dc084bf50/source/app/titles.cpp#L60

**Comment by Crementif** [comment]
Should be fixed in the latest release. Let me know if it's working now, and if not I'll spend some more time on it.

**Comment by redman-tsai** [comment]
thanks for the quick fix, I have just tested, it is working perfectly well now.
