### ISSUE TITLE
Dumping over IP

### ISSUE THREAD

**Issue by 1upbyte** [emiyl/dumpling#34]
Hey! Is implementing a way to dump to an FTP server or SMB share doable? It would allow direct dumping to systems rather than having to pass through a (usually slow) USB or SD card.

**Comment by Crementif** [comment]
Wireless dumping is a long time goal, but it definitely won't be faster then the very specialized fat32 dumping that I added in the latest revision.

**Comment by 1upbyte** [comment]
Oh wow is it that good? I'm about to dump my entire collection. I remember waiting hours to dump a game only for it to fail :(

**Comment by Crementif** [comment]
The Wii U still doesn't have the highest throughput, and the wifi/ethernet/usb output it has is still limited to a max of 10mb roughly.

**Comment by 1upbyte** [comment]
Yikes...
